# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en
  menu:
    main:
    - name: Introduction
      url: /
      weight: 10
    - name: Experience
      url: experience/
      weight: 20
    - identifier: projects
      name: Projects
      weight: 30
    - name: Backend
      parent: projects
      url: backend-projects/
      weight: 31
    - name: Frontend
      parent: projects
      url: frontend-projects/
      weight: 32
    - name: Other
      parent: projects
      url: other-projects/
      weight: 33
    - name: Skills
      url: skills/
      weight: 40
    - name: Contact
      url: contact/
      weight: 50


ko:
  languageCode: ko
  contentDir: content/ko
  title: 한국어 웹사이트 제목
  params:
    description: 한국어로 된 사이트 설명...
  menu:
    main:
      - name: 소개
        url: /
        weight: 10
      - name: 경험
        url: experience/
        weight: 20
      - identifier: projects
        name: 프로젝트
        weight: 30
      - name: 백엔드
        parent: projects
        url: backend-projects/
        weight: 31
      - name: 프론트엔드
        parent: projects
        url: frontend-projects/
        weight: 32
      - name: 기타
        parent: projects
        url: other-projects/
        weight: 33
      - name: 기술
        url: skills/
        weight: 40
      - name: 연락
        url: contact/
        weight: 50
