# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: '진덕종, Jin Deokjong, 陳德宗, 전북대학교 진덕종, 전북대, Jeonbuk National University, JBNU Jin Deokjong, JBNU Jin Deokjong CV, JBNU Jin Deokjong Curriculum Vitae, JBNU Jin Deokjong Resume, JBNU Jin Deokjong Profile, JBNU Jin Deokjong Homepage, JBNU Jin Deokjong Personal Website, JBNU Jin Deokjong Personal Homepage, JBNU Jin Deokjong Personal Site, JBNU Jin Deokjong Personal Webpage, JBNU Jin Deokjong Personal CV, JBNU Jin Deokjong Personal Curriculum Vitae, JBNU Jin Deokjong Personal Resume, JBNU Jin Deokjong Personal Profile, JBNU Jin Deokjong Personal Academic Website, JBNU Jin Deokjong Personal Academic Homepage, JBNU Jin Deokjong Personal Academic Site, JBNU Jin Deokjong Personal Academic Webpage, JBNU Jin Deokjong Personal Academic CV, JBNU Jin Deokjong Personal Academic Curriculum Vitae, JBNU Jin Deokjong Personal Academic Resume, JBNU Jin Deokjong Personal Academic Profile, JBNU Jin Deokjong Personal Academic CV, JBNU Jin Deokjong Personal Academic Curriculum Vitae, JBNU Jin Deokjong Personal Academic Resume, JBNU Jin Deokjong Personal Academic Profile, 진덕종 CV, 진덕종 Curriculum Vitae, 진덕종 Resume, 진덕종 Profile, 진덕종 Homepage, 진덕종 Personal Website, 진덕종 Personal Homepage, 진덕종 Personal Site, 진덕종 Personal Webpage, 진덕종 Personal CV, 진덕종 Personal Curriculum Vitae, 진덕종 Personal Resume, 진덕종 Personal Profile, 진덕종 Personal Academic Website, 진덕종 Personal Academic Homepage, 진덕종 Personal Academic Site, 진덕종 Personal Academic Webpage, 진덕종 Personal Academic CV, 진덕종 Personal Academic Curriculum Vitae, 진덕종 Personal Academic Resume, 진덕종 Personal Academic Profile, 진덍종 Personal Academic CV, 진덕종 Personal Academic Curriculum Vitae, 진덕종 Personal Academic Resume, 진덕종 Personal Academic Profile, Jin Deokjong CV, Jin Deokjong Curriculum Vitae, Jin Deokjong Resume, Jin Deokjong Profile, Jin Deokjong Homepage, Jin Deokjong Personal Website, Jin Deokjong Personal Homepage, Jin Deokjong Personal Site, Jin Deokjong Personal Webpage, Jin Deokjong Personal CV, Jin Deokjong Personal Curriculum Vitae, Jin Deokjong Personal Resume, Jin Deokjong Personal Profile, Jin Deokjong Personal Academic Website, Jin Deokjong Personal Academic Homepage, Jin Deokjong Personal Academic Site, Jin Deokjong Personal Academic Webpage, Jin Deokjong Personal Academic CV, Jin Deokjong Personal Academic Curriculum Vitae, Jin Deokjong Personal Academic Resume, Jin Deokjong Personal Academic Profile, Jin Deokjong Personal Academic CV, Jin Deokjong Personal Academic Curriculum Vitae, Jin Deokjong Personal Academic Resume, Jin Deokjong Personal Academic Profile, Jin Deokjong CV, Jin Deokjong Curriculum Vitae, Jin Deokjong Resume, Jin Deokjong Profile, Jin Deokjong Homepage, Jin Deokjong Personal Website, Jin Deokjong Personal Homepage, 전북대 진덕종, 전북대 진덕종 CV, 전북대 진덕종 Curriculum Vitae, 전북대 진덕종 Resume, 전북대 진덕종 Profile, 전북대 진덕종 Homepage, 전북대 진덕종 Personal Website, 전북대 진덕종 Personal Homepage, 전북대 진덕종 Personal Site, 전북대 진덕종 Personal Webpage, 전북대 진덕종 Personal CV, 전북대 진덕종 Personal Curriculum Vitae, 전북대 진덕종 Personal Resume, 전북대 진덕종 Personal Profile, 전북대 진덕종 Personal Academic Website, 전북대 진덕종 Personal Academic Homepage, 전북대 진덕종 Personal Academic Site, 전북대 진덕종 Personal Academic Webpage, 전북대 진덕종 Personal Academic CV, 전북대 진덕종 Personal Academic Curriculum Vitae, 전북대 진덕종 Personal Academic Resume, 전북대 진덕종 Personal Academic Profile, 전북대 진덕종 Personal Academic CV, 전북대 진덕종 Personal Academic Curriculum Vitae, 전북대 진덕종 Personal Academic Resume, 전북대 진덕종 Personal Academic Profile, 전북대 진덕종 CV, 전북대 진덕종 Curriculum Vitae, 전북대 진덕종 Resume, 전북대 진덕종 Profile, 전북대 진덕종 Homepage, 전북대 진덕종 Personal Website, 전북대 진덕종 Personal Homepage, 전북대 진덕종 Personal Site, 전북대 진덕종 Personal Webpage'
    description: '전북대학교 진덕종의 이력서 사이트입니다.'
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: '4fAVBwDWP6nKjmOBcBebl36BiHQtYJ2x'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Jin Deokjong"

# Site footer
footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
